### ISSUE TITLE
got error `Exception encountered during context initialization - cancelling refresh attempt`

### ISSUE THREAD

**Issue by ardihikaru** [ehrbase/ehrbase#1061]
Hello. I got an issue when using this ehrbase service on my project.
How can I `fix` or `prevent` this error to happen?

# Environment information

> Here are my environments (run under `GCP SQL`)
- EHRbase version: `0.24.0-SNAPSHOT`
- openEHR_SDK version: `1.24.0-SNAPSHOT`
- Archie version: `2.0.1`
- PostgreSQL version: `PostgreSQL 14.4 on x86_64-pc-linux-gnu, compiled by Debian clang version 12.0.1, 64-bit`
- Java Runtime version: `Eclipse Adoptium 17.0.6+10`
- Operating System version: `Linux amd64 5.15.0-58-generic`

# Steps to reproduce

> Everything was working normally, it suddenly got error as follows:
```
2023-02-20 06:55:28.146  INFO [] 9 --- [pool-1-thread-1] o.ehrbase.service.KnowledgeCacheService  : Updating WebTemplate cache for template: xxxxxxx-v1.1.1

2023-02-20 06:55:42.369  WARN [] 9 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webConfiguration' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/classes!/org/ehrbase/application/config/web/WebConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ehrService' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.24.0-SNAPSHOT.jar!/org/ehrbase/service/EhrServiceImp.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'knowledgeCacheService' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.24.0-SNAPSHOT.jar!/org/ehrbase/service/KnowledgeCacheService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ehrbase.service.KnowledgeCacheService]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "org.jooq.DSLContext.fetchOptional(org.jooq.Table, org.jooq.Condition)" because the return value of "org.ehrbase.dao.access.interfaces.I_DomainAccess.getContext()" is null
2023-02-20 06:55:42.373  INFO [] 9 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-02-20 06:55:42.395  INFO [] 9 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2023-02-20 06:55:42.403  INFO [] 9 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-02-20 06:55:42.455  INFO [] 9 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-02-20 06:55:42.538 ERROR [] 9 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webConfiguration' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/classes!/org/ehrbase/application/config/web/WebConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ehrService' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.24.0-SNAPSHOT.jar!/org/ehrbase/service/EhrServiceImp.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'knowledgeCacheService' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.24.0-SNAPSHOT.jar!/org/ehrbase/service/KnowledgeCacheService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ehrbase.service.KnowledgeCacheService]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "org.jooq.DSLContext.fetchOptional(org.jooq.Table, org.jooq.Condition)" because the return value of "org.ehrbase.dao.access.interfaces.I_DomainAccess.getContext()" is null
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at org.ehrbase.application.EhrBase.main(EhrBase.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ehrService' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.24.0-SNAPSHOT.jar!/org/ehrbase/service/EhrServiceImp.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'knowledgeCacheService' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.24.0-SNAPSHOT.jar!/org/ehrbase/service/KnowledgeCacheService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ehrbase.service.KnowledgeCacheService]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "org.jooq.DSLContext.fetchOptional(org.jooq.Table, org.jooq.Condition)" because the return value of "org.ehrbase.dao.access.interfaces.I_DomainAccess.getContext()" is null
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'knowledgeCacheService' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.24.0-SNAPSHOT.jar!/org/ehrbase/service/KnowledgeCacheService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ehrbase.service.KnowledgeCacheService]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "org.jooq.DSLContext.fetchOptional(org.jooq.Table, org.jooq.Condition)" because the return value of "org.ehrbase.dao.access.interfaces.I_DomainAccess.getContext()" is null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 41 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ehrbase.service.KnowledgeCacheService]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "org.jooq.DSLContext.fetchOptional(org.jooq.Table, org.jooq.Condition)" because the return value of "org.ehrbase.dao.access.interfaces.I_DomainAccess.getContext()" is null
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	... 55 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.DSLContext.fetchOptional(org.jooq.Table, org.jooq.Condition)" because the return value of "org.ehrbase.dao.access.interfaces.I_DomainAccess.getContext()" is null
	at org.ehrbase.dao.access.interfaces.I_ConceptAccess.loadConcept(I_ConceptAccess.java:136)
	at org.ehrbase.dao.access.interfaces.I_ConceptAccess.lambda$getConceptByConceptId$0(I_ConceptAccess.java:110)
	at org.ehrbase.service.KnowledgeCacheService.getConceptByConceptId(KnowledgeCacheService.java:596)
	at org.ehrbase.dao.access.interfaces.I_ConceptAccess.getConceptByConceptId(I_ConceptAccess.java:109)
	at org.ehrbase.dao.access.interfaces.I_ConceptAccess.fetchContributionChangeType(I_ConceptAccess.java:102)
	at org.ehrbase.service.KnowledgeCacheService.lambda$initializeCaches$2(KnowledgeCacheService.java:230)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.ehrbase.service.KnowledgeCacheService.initializeCaches(KnowledgeCacheService.java:230)
	at org.ehrbase.service.KnowledgeCacheService.<init>(KnowledgeCacheService.java:151)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 57 common frames omitted
```

# Actual result

> There should be no such error above

# Expected result

> No error on the logs

```
2023-02-20 06:59:37.168  INFO [] 8 --- [pool-2-thread-1] o.ehrbase.service.KnowledgeCacheService  : Updating WebTemplate cache for template: xxxxxxxxxv4
2023-02-20 06:59:37.477  INFO [] 8 --- [pool-2-thread-1] o.ehrbase.service.KnowledgeCacheService  : Updating WebTemplate cache for template: yyyyyyy-v1
2023-02-20 06:59:38.749  WARN [] 8 --- [           main] o.e.a.c.s.NoOpSecurityConfiguration      : Security is disabled. Configure 'security.auth-type' to disable this warning.
2023-02-20 06:59:38.972  WARN [] 8 --- [           main] uration$$EnhancerBySpringCGLIB$$18007823 : External terminology validation is disabled, consider to enable it
2023-02-20 06:59:41.119  INFO [] 8 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 0 endpoint(s) beneath base path '/management'
2023-02-20 06:59:41.199  INFO [] 8 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path '/ehrbase'
2023-02-20 06:59:41.220  INFO [] 8 --- [           main] org.ehrbase.application.EhrBase          : Started EhrBase in 14.937 seconds (JVM running for 15.797)
2023-02-20 07:00:45.755  INFO [] 8 --- [nio-8080-exec-4] o.a.c.c.C.[.[localhost].[/ehrbase]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-02-20 07:00:45.755  INFO [] 8 --- [nio-8080-exec-4] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-02-20 07:00:45.760  INFO [] 8 --- [nio-8080-exec-4] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
```

# Further information

> n/a

**Comment by stefanspiska** [comment]
`"org.ehrbase.dao.access.interfaces.I_DomainAccess.getContext()" is null`

points to that  something went wrong  during getting the db connections,

**Comment by ardihikaru** [comment]
hi @stefanspiska . thanks for reaching me out.

how to debug or make sure that the db connection is the problem?

**Comment by ardihikaru** [comment]
yes. something similar. and we deployed them on top of kubernetes.
this issue happens after few days since the ehrbase service running.
it was working for few days. however, it just got corrupted like that after few days, even with a few workload (no one using it)

**Comment by stefanspiska** [comment]
Hm,

What I can tell you is that we have several long running system ón kubernetes and never encountered a error like that that. 

The only advice I can give is to use remote debugging to check what's happening on the pod and if the Db is  reachable from it.

**Comment by ardihikaru** [comment]
hi @stefanspiska @vladislavploaia 
thanks for the responses again.

> The only advice I can give is to use remote debugging to check what's happening on the pod and if the Db is reachable from it.
I don't get it here. do you mean to suggest I tunnel the database and try connecting it locally? or did I get it wrong?

**Comment by vidi42** [comment]
@ardihikaru sorry for the late reply

What @stefanspiska meant was to start EHRbase in debug mode, connect with a remote debugger to it, and go step by step to see what might cause the issue during start-up.
As mentioned, we have not encountered it in our environments so we cannot provide further support until more context is provided. Our best assumption is that the connection to the DB cannot be performed.

**Comment by manci22lc** [comment]
Hi  @stefanspiska @vladislavploaia @vidi42 ,

We are also facing the same issue,
We have migrated data from v20 to v26 and have around 100 templates , during start up when knowledgeCache is getting initialized, it crashes abruptly with above error mentioned in this thread , and its not consistent on which template it crashes (for e.g. it abruptly fails after loading multiple templates, it crashes after loading 80 templates or sometimes around 89 or even after loading all templates. There is no fixed threshold of templates to be loaded).

On debugging code/retracing logs 
On Class KnowledgeCacheService, method initializeCaches, it fails on these lines of code 

_" List.of(I_ConceptAccess.ContributionChangeType.values())
                .forEach(c -> I_ConceptAccess.fetchContributionChangeType(domainAccess, c));"_
                
     Here domainAccess is null, as dslContext which is autowired in return gives back null.

But our understanding is:
1. initCachePerTenant is called asynchronously
2. code  checks if the threads execution was completed
    - if the execution is successful, the return statements is executed
    - Otherwise, if the templates to be loaded are higher in number or time execution taken is longer than usual, it does not execute the return statement, instead it continues with the rest of the execution of code and fails at the line given above.

Any insights on the above could be really useful for our Migration.

Thanks

**Comment by manci22lc** [comment]
@stefanspiska , tried with said approach, still facing the same issue.

**Comment by stefanspiska** [comment]
@manci22lc 

please check with https://github.com/ehrbase/ehrbase/pull/1101 this should fix the bug.

**Comment by manci22lc** [comment]
@stefanspiska , As suggested have taken fix from #1101 , Getting below error 

<code>
java.lang.IllegalArgumentException: Cannot translate a null SQLException
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:68)
	at org.ehrbase.service.PersistenceConfig$ExceptionTranslator.exception(PersistenceConfig.java:50)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:276)
	at org.jooq.impl.Tools.exception(Tools.java:2513)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2449)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2417)
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4769)
	at org.jooq.impl.DefaultDSLContext.fetchOptional(DefaultDSLContext.java:4933)
	at org.ehrbase.dao.access.interfaces.I_ConceptAccess.loadConcept(I_ConceptAccess.java:137)
	at org.ehrbase.dao.access.interfaces.I_ConceptAccess.lambda$0(I_ConceptAccess.java:111)
	at org.ehrbase.service.KnowledgeCacheService.getConceptByConceptId(KnowledgeCacheService.java:609)
	at org.ehrbase.dao.access.interfaces.I_ConceptAccess.getConceptByConceptId(I_ConceptAccess.java:110)
	at org.ehrbase.dao.access.interfaces.I_ConceptAccess.fetchContributionChangeType(I_ConceptAccess.java:103)
	at org.ehrbase.service.KnowledgeCacheService.lambda$0(KnowledgeCacheService.java:227)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.ehrbase.service.KnowledgeCacheService.initializeCaches(KnowledgeCacheService.java:227)
	at org.ehrbase.service.KnowledgeCacheService.init(KnowledgeCacheService.java:157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at org.ehrbase.application.EhrBase.main(EhrBase.java:44)

</code>

**Comment by stefanspiska** [comment]
@manci22lc 

please re-check with https://github.com/ehrbase/ehrbase/pull/1101/commits/a927c935f5e2055dd04bd9fce0337f4114950418

**Comment by manci22lc** [comment]
@stefanspiska , this commit https://github.com/ehrbase/ehrbase/commit/a927c935f5e2055dd04bd9fce0337f4114950418, works, Thank you.

**Comment by manci22lc** [comment]
@stefanspiska ,
Can you please let us know when can we expect this fix, or when v27 release planned ?

**Comment by vidi42** [comment]
@manci22lc we testing internally the release candidate for v0.27. This will be coming out before the end of this month.

**Comment by ardihikaru** [comment]
sorry, I got lost on the issue's track here.
I am currently still using the old version.
Many thanks, @stefanspiska for the awesome support.
I will try [a927c93](https://github.com/ehrbase/ehrbase/commit/a927c935f5e2055dd04bd9fce0337f4114950418) as per confirmed by @manci22lc that this fix solved the mentioned bug in my issue.

**Comment by vidi42** [comment]
@ardihikaru this should be part of the latest ehrbase release [0.27.0](https://github.com/ehrbase/ehrbase/releases/tag/v0.27.0)

**Comment by ardihikaru** [comment]
Hi @vidi42 .
yeah, just checked the docker hub that I can use the latest ehrbase release [0.27.0](https://github.com/ehrbase/ehrbase/releases/tag/v0.27.0). Thanks a lot.
