### ISSUE TITLE
Error when generating example compostion - Cannot invoke "String.startsWith(String)" because "nodeId" is null

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#1151]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

```xml
<status>
	<ehrbase_version>0.27.0-SNAPSHOT</ehrbase_version>
	<openehr_sdk_version>1.27.0-SNAPSHOT</openehr_sdk_version>
	<archie_version>3.0.0</archie_version>
	<jvm_version>Eclipse Adoptium 17.0.6+10</jvm_version>
	<os_version>Linux aarch64 5.10.124-linuxkit</os_version>
	<postgres_version>PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit</postgres_version>
</status>
```

### Steps to reproduce

Post OPT:
[kenko i3.opt.txt](https://github.com/ehrbase/ehrbase/files/12122975/kenko.i3.opt.txt)

GET {{ehrscapeBaseUrl}}/template/{{templateId}}/example?format=FLAT

### Expected behavior

200 OK

### Actual result

2023-07-21 11:15:09.119 ERROR [traceId=3fbc5c483edc889f] 8 --- [io-8080-exec-59] o.e.r.ehrscape.EhrScapeExceptionHandler  : 

java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "nodeId" is null
  at org.ehrbase.webtemplate.parser.NodeId.<init>(NodeId.java:33)
  at org.ehrbase.serialisation.walker.ToCompositionWalker.postHandle(ToCompositionWalker.java:76)
  at org.ehrbase.openehr.sdk.examplegenerator.ExampleGeneratorToCompositionWalker.postHandle(ExampleGeneratorToCompositionWalker.java:128)
  at org.ehrbase.serialisation.walker.Walker.handle(Walker.java:157)
  at org.ehrbase.serialisation.walker.Walker.lambda$handle$2(Walker.java:153)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
  at org.ehrbase.serialisation.walker.Walker.handle(Walker.java:145)
  at org.ehrbase.serialisation.walker.Walker.lambda$handle$2(Walker.java:153)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
  at org.ehrbase.serialisation.walker.Walker.handle(Walker.java:145)
  at org.ehrbase.serialisation.walker.Walker.walk(Walker.java:93)
  at org.ehrbase.serialisation.walker.Walker.walk(Walker.java:70)
  at org.ehrbase.service.TemplateServiceImp.buildExample(TemplateServiceImp.java:127)
  at org.ehrbase.service.TemplateServiceImp$$FastClassBySpringCGLIB$$a3b4bf62.invoke(<generated>)
  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
  at org.ehrbase.service.TemplateServiceImp$$EnhancerBySpringCGLIB$$6870156.buildExample(<generated>)
  at org.ehrbase.rest.ehrscape.controller.TemplateController.getTemplateExample(TemplateController.java:112)
  at org.ehrbase.rest.ehrscape.controller.TemplateController$$FastClassBySpringCGLIB$$e713f693.invoke(<generated>)
  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
  at org.ehrbase.tenant.DefaultTenantAspect.action(DefaultTenantAspect.java:87)
  at org.ehrbase.tenant.DefaultTenantAspect.action(DefaultTenantAspect.java:70)
  at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
  at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
  at org.ehrbase.rest.ehrscape.controller.TemplateController$$EnhancerBySpringCGLIB$$a88703e4.getTemplateExample(<generated>)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)

**Comment by vladislavploaia** [comment]
Hello @sidharthramesh ,
Thank you for this ticket.
JIRA ticket reported internally as well, for tracking purposes.
https://vitagroup-ag.atlassian.net/browse/CDR-967
Will let you know once I have any updates on it.
CC: @vidi42 , @stefanspiska

**Comment by vidi42** [comment]
@sidharthramesh feedback from the team

> content[openEHR-EHR-ADMIN_ENTRY.i3_hosptil_bill.v0]/data is an ITEM_TREE yet does not contain an  
node_id and is thus not a valid template
