### ISSUE TITLE
Error when posting compostion - Cannot invoke "String.startsWith(String)" because "nodeId" is null

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#1152]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

```xml
<status>
	<ehrbase_version>0.27.0-SNAPSHOT</ehrbase_version>
	<openehr_sdk_version>1.27.0-SNAPSHOT</openehr_sdk_version>
	<archie_version>3.0.0</archie_version>
	<jvm_version>Eclipse Adoptium 17.0.6+10</jvm_version>
	<os_version>Linux aarch64 5.10.124-linuxkit</os_version>
	<postgres_version>PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit</postgres_version>
</status>
```

### Steps to reproduce

Use template - 
[kenko i3.opt.txt](https://github.com/ehrbase/ehrbase/files/12135832/kenko.i3.opt.txt)

Post FLAT composition:

```json
{
	"kenko_i3/category|code": "433",
	"kenko_i3/category|value": "event",
	"kenko_i3/category|terminology": "openehr",
	"kenko_i3/context/start_time": "2021-11-11T12:33:45.234Z",
	"kenko_i3/context/setting|code": "238",
	"kenko_i3/context/setting|value": "other care",
	"kenko_i3/context/setting|terminology": "openehr",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/payability|code": "at0043",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/payability|value": "PP",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/payability|terminology": "local",
	"kenko_i3/i3_hosptil_bill/approve": "Yes",
	"kenko_i3/i3_hosptil_bill/draft": "No",
	"kenko_i3/i3_hosptil_bill/case_id": "1ede342",
	"kenko_i3/i3_hosptil_bill/bed_number": "12",
	"kenko_i3/i3_hosptil_bill/i3_case_id": "8uh34r",
	"kenko_i3/i3_hosptil_bill/status": "Porgress",
	"kenko_i3/i3_hosptil_bill/financial_summary": "dyuehbwneui",
	"kenko_i3/i3_hosptil_bill/deduction_summary": "dsfed2wrafead",
	"kenko_i3/i3_hosptil_bill/bill_details:0/bill_id": "12313",
	"kenko_i3/i3_hosptil_bill/bill_details:0/bill_number": "54321",
	"kenko_i3/i3_hosptil_bill/bill_details:0/bill_type": "Bill",
	"kenko_i3/i3_hosptil_bill/bill_details:0/pre-post": "Yes",
	"kenko_i3/i3_hosptil_bill/bill_details:0/duplicate_bill": "No",
	"kenko_i3/i3_hosptil_bill/bill_details:0/invalide_bill": "No",
	"kenko_i3/i3_hosptil_bill/bill_details:0/reason_for_invalid_bill": "No reason",
	"kenko_i3/i3_hosptil_bill/bill_details:0/detailed_reason_for_invalid_bill": "No reason",
	"kenko_i3/i3_hosptil_bill/bill_details:0/file_name": "123.pdf",
	"kenko_i3/i3_hosptil_bill/bill_details:0/bill_page_number": "12",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/item_id": "medicine",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/item": "Medicine",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/level_1_item": "Medicine 1",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/level_2_item": "Medicine 2",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/level_3_item": "Medicine 3",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/reason_for_partially_payable": "No reason",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/detailed_reason_for_partially_payable": "No reason",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/reason_for_non_payable": "No reason",
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/detailed_reason_for_non_payable": "No reason",
	"kenko_i3/i3_hosptil_bill/date_of_admission": "2023-07-13T05:27:00.000Z",
	"kenko_i3/i3_hosptil_bill/date_of_discharge": "2023-07-12T05:27:00.000Z",
	"kenko_i3/i3_hosptil_bill/bill_details:0/bill_date": "2023-07-19",
	"kenko_i3/i3_hosptil_bill/proportionate_deduction_ratio|numerator": 10,
	"kenko_i3/i3_hosptil_bill/proportionate_deduction_ratio|denominator": 100,
	"kenko_i3/i3_hosptil_bill/proportionate_deduction_ratio|type": 2,
	"kenko_i3/i3_hosptil_bill/copay|numerator": 10,
	"kenko_i3/i3_hosptil_bill/copay|denominator": 100,
	"kenko_i3/i3_hosptil_bill/copay|type": 2,
	"kenko_i3/i3_hosptil_bill/bill_details:0/discount_percentage|numerator": 1,
	"kenko_i3/i3_hosptil_bill/bill_details:0/discount_percentage|denominator": 100,
	"kenko_i3/i3_hosptil_bill/bill_details:0/discount_percentage|type": 2,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/payability_percent|numerator": 12,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/payability_percent|denominator": 100,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/payability_percent|type": 2,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/deduction_ratio|numerator": 12,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/deduction_ratio|denominator": 100,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/deduction_ratio|type": 2,
	"kenko_i3/i3_hosptil_bill/total_amount": 10000,
	"kenko_i3/i3_hosptil_bill/total_non_payable_deductions": 1000,
	"kenko_i3/i3_hosptil_bill/deductible": 1000,
	"kenko_i3/i3_hosptil_bill/treatment_benefit_amount": 9000,
	"kenko_i3/i3_hosptil_bill/treatment_benefit_utilised": 1003,
	"kenko_i3/i3_hosptil_bill/plan_benefit_amount": 12312,
	"kenko_i3/i3_hosptil_bill/plan_benefit_utilized": 4123,
	"kenko_i3/i3_hosptil_bill/final_payable": 10000,
	"kenko_i3/i3_hosptil_bill/final_payable_after_deductions": 9000,
	"kenko_i3/i3_hosptil_bill/non_payable_deduction_amount": 1000,
	"kenko_i3/i3_hosptil_bill/proportionate_deduction_amount": 200,
	"kenko_i3/i3_hosptil_bill/copay_deduction_amount": 900,
	"kenko_i3/i3_hosptil_bill/deductible_deduction_amount": 800,
	"kenko_i3/i3_hosptil_bill/treatment_plan_deduction_amount": 1231,
	"kenko_i3/i3_hosptil_bill/amount_before_copay": 423,
	"kenko_i3/i3_hosptil_bill/amount_after_copay": 21321,
	"kenko_i3/i3_hosptil_bill/amount_after_deducitble": 1231,
	"kenko_i3/i3_hosptil_bill/deduction_through_deductible": 43,
	"kenko_i3/i3_hosptil_bill/deduction_through_copay": 5678,
	"kenko_i3/i3_hosptil_bill/amount_before_deductible": 678,
	"kenko_i3/i3_hosptil_bill/room_rent_given_limit": 1000,
	"kenko_i3/i3_hosptil_bill/room_rent_per_day": 100,
	"kenko_i3/i3_hosptil_bill/bill_details:0/bill_amount": 1000,
	"kenko_i3/i3_hosptil_bill/bill_details:0/bill_discount": 200,
	"kenko_i3/i3_hosptil_bill/bill_details:0/payable_sum": 234,
	"kenko_i3/i3_hosptil_bill/bill_details:0/discount_amount": 0,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/quantity": 4,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/amount": 30,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/net_amount": 120,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/max_payable_amount": 412,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/item_payable_sum": 100,
	"kenko_i3/i3_hosptil_bill/bill_details:0/item_details:0/deduction_amount": 300,
	"kenko_i3/i3_hosptil_bill/language|code": "en",
	"kenko_i3/i3_hosptil_bill/language|terminology": "ISO_639-1",
	"kenko_i3/i3_hosptil_bill/encoding|code": "UTF-8",
	"kenko_i3/i3_hosptil_bill/encoding|terminology": "IANA_character-sets",
	"kenko_i3/composer|name": "Medblocks UI",
	"kenko_i3/language|code": "en",
	"kenko_i3/language|terminology": "ISO_639-1",
	"kenko_i3/territory|code": "IN",
	"kenko_i3/territory|terminology": "ISO_3166-1"
}
```

### Expected behavior

200 OK

### Actual result

500 Internal Server Error

```json
{
	"error": "Internal Server Error",
	"message": "An internal error has occurred. Please contact your administrator."
}
```

with logs:

```
023-07-22 06:23:22.172 ERROR [traceId=5bffd83374f0903d] 8 --- [io-8080-exec-57] o.e.r.ehrscape.EhrScapeExceptionHandler  : 
ava.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "nodeId" is null
  at org.ehrbase.webtemplate.parser.NodeId.<init>(NodeId.java:33)
  at org.ehrbase.serialisation.walker.ToCompositionWalker.postHandle(ToCompositionWalker.java:76)
  at org.ehrbase.serialisation.flatencoding.std.umarshal.StdToCompositionWalker.postHandle(StdToCompositionWalker.java:309)
  at org.ehrbase.serialisation.walker.Walker.handle(Walker.java:157)
  at org.ehrbase.serialisation.walker.Walker.lambda$handle$2(Walker.java:153)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
  at org.ehrbase.serialisation.walker.Walker.handle(Walker.java:145)
  at org.ehrbase.serialisation.walker.Walker.lambda$handle$2(Walker.java:153)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
  at org.ehrbase.serialisation.walker.Walker.handle(Walker.java:145)
  at org.ehrbase.serialisation.walker.Walker.walk(Walker.java:93)
  at org.ehrbase.serialisation.walker.Walker.walk(Walker.java:70)
  at org.ehrbase.serialisation.flatencoding.std.umarshal.StdToCompositionWalker.walk(StdToCompositionWalker.java:98)
  at org.ehrbase.serialisation.flatencoding.std.umarshal.FlatJsonUnmarshaller.unmarshal(FlatJsonUnmarshaller.java:85)
  at org.ehrbase.serialisation.flatencoding.FlatJson.unmarshal(FlatJson.java:64)
  at org.ehrbase.service.CompositionServiceImp.buildComposition(CompositionServiceImp.java:588)
  at org.ehrbase.service.CompositionServiceImp$$FastClassBySpringCGLIB$$9bcfd210.invoke(<generated>)
  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
  at org.ehrbase.service.CompositionServiceImp$$EnhancerBySpringCGLIB$$2b110506.buildComposition(<generated>)
  at org.ehrbase.rest.ehrscape.controller.CompositionController.createComposition(CompositionController.java:84)
  at org.ehrbase.rest.ehrscape.controller.CompositionController$$FastClassBySpringCGLIB$$62ce38e9.invoke(<generated>)
  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
  at org.ehrbase.tenant.DefaultTenantAspect.action(DefaultTenantAspect.java:87)
  at org.ehrbase.tenant.DefaultTenantAspect.action(DefaultTenantAspect.java:70)
  at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
  at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
  at org.ehrbase.rest.ehrscape.controller.CompositionController$$EnhancerBySpringCGLIB$$ef6ef0a6.createComposition(<generated>)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
  at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
  at org.ehrbase.application.web.LoggingContextFilter.doFilterInternal(LoggingContextFilter.java:55)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
  at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:156)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
  at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
  at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by vladislavploaia** [comment]
Hello @sidharthramesh,
It seems to be the same as in [issues/1151](https://github.com/ehrbase/ehrbase/issues/1151).
Once [issues/1151] is fixed, I will check it as well (POST Composition).
JIRA ticket will not be opened for this case.
Thank you!
CC: @vidi42 , @stefanspiska

**Comment by vladislavploaia** [comment]
Hello @sidharthramesh ,
https://github.com/ehrbase/ehrbase/issues/1151 - is closed.
See below comments.
![image](https://github.com/ehrbase/ehrbase/assets/100927963/4d2cc2ff-ac5c-40bb-b776-6acd2952c2e1)
Closing this ticket as well, as it is duplicated.
CC: @vidi42 , @stefanspiska
