### ISSUE TITLE
Error retrieving posted composition

### ISSUE THREAD

**Issue by abhinandkrish** [ehrbase/ehrbase#1165]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

ehrbase_version: 0.22.0
openehr_sdk_version: 1.23.0
archie_version: 2.0.1
jvm_version: Oracle Corporation 11.0.16+8
os_version: Linux amd64 5.15.107+
postgres_version: PostgreSQL 14.7 (Ubuntu 14.7-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit

### Steps to reproduce

crate a composition using the opt.
[tacten.mb.v0.opt.zip](https://github.com/ehrbase/ehrbase/files/12358829/tacten.mb.v0.opt.zip)

The resource got posted in ehrbase.

The resource exists in entry table as 
[rawComp.json.zip](https://github.com/ehrbase/ehrbase/files/12358851/rawComp.json.zip)

But could not retrieve the resource.

### Expected behavior

The posted composition on GET request.

### Actual result

The GET for both openehr and ecis requests gets erroring out with error
`{
	"error": "Bad Request",
	"message": "DB inconsistency:java.lang.IllegalArgumentException: Could not resolve subtype of [simple type, class com.nedap.archie.rm.datastructures.Item]: missing type id property '_type' (for POJO property 'items')\n at [Source: (StringReader); line: 3, column: 26046] (through reference chain: com.nedap.archie.rm.composition.Composition[\"content\"]->java.util.ArrayList[8]->com.nedap.archie.rm.composition.Instruction[\"activities\"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Activity[\"description\"]->com.nedap.archie.rm.datastructures.ItemTree[\"items\"]->java.util.ArrayList[3]->com.nedap.archie.rm.datastructures.Cluster[\"items\"]->java.util.ArrayList[0])"
}`

**Comment by vidi42** [comment]
@abhinandkrish I see you are using EHRbase 0.22.0, which is pretty old right now. Any chance you could test this on the latest version, 0.30.0?

**Comment by abhinandkrish** [comment]
I tried converting the raw composition to structured string using the latest 
org.ehrbase.openehr.sdk version 2.2.0
org.ehrbase.openehr version 0.30.0
org.ehrbase.openehr version 3.5.0

`package com.medblocks;

import java.nio.file.Files;
import java.nio.file.Paths;

import static java.nio.charset.StandardCharsets.UTF_8;

import org.ehrbase.jooq.dbencoding.rawjson.LightRawJsonEncoder;
import org.ehrbase.openehr.sdk.response.dto.ehrscape.StructuredString;
import org.ehrbase.openehr.sdk.response.dto.ehrscape.StructuredStringFormat;
import org.ehrbase.openehr.sdk.serialisation.jsonencoding.CanonicalJson;

import com.nedap.archie.rm.composition.Composition;

public class compTrial {
   public static void main(String[] args) {
      String filePath = "rawComp.json";
      try {
         String db_encoded = new String(Files.readAllBytes(Paths.get(filePath)), UTF_8);

         String comp = convertToComposition(db_encoded);

         System.out.println(comp);

      } catch (Exception e) {
         e.printStackTrace();
      }
   }

   public static String convertToComposition(String db_encoded) {
      String converted = new LightRawJsonEncoder(db_encoded).encodeCompositionAsString();

      Composition composition = new CanonicalJson().unmarshal(converted, Composition.class);

      StructuredString structuredString = new StructuredString(new CanonicalJson().marshal(composition),
            StructuredStringFormat.JSON);
            
      return structuredString.getValue();
   }
}
`
The composition is still erroring out with :
`org.ehrbase.openehr.sdk.serialisation.exception.UnmarshalException: Could not resolve subtype of [simple type, class com.nedap.archie.rm.datastructures.Item]: missing type id property '_type' (for POJO property 'items')
 at [Source: (StringReader); line: 3, column: 26147] (through reference chain: com.nedap.archie.rm.composition.Composition["content"]->java.util.ArrayList[8]->com.nedap.archie.rm.composition.Instruction["activities"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Activity["description"]->com.nedap.archie.rm.datastructures.ItemTree["items"]->java.util.ArrayList[3]->com.nedap.archie.rm.datastructures.Cluster["items"]->java.util.ArrayList[0])
        at org.ehrbase.openehr.sdk.serialisation.jsonencoding.CanonicalJson.unmarshal(CanonicalJson.java:143)
        at com.medblocks.compTrial.convertToComposition(compTrial.java:33)
        at com.medblocks.compTrial.main(compTrial.java:21)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class com.nedap.archie.rm.datastructures.Item]: missing type id property '_type' (for POJO property 'items')
 at [Source: (StringReader); line: 3, column: 26147] (through reference chain: com.nedap.archie.rm.composition.Composition["content"]->java.util.ArrayList[8]->com.nedap.archie.rm.composition.Instruction["activities"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Activity["description"]->com.nedap.archie.rm.datastructures.ItemTree["items"]->java.util.ArrayList[3]->com.nedap.archie.rm.datastructures.Cluster["items"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
        at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:2088)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1601)
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:307)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:185)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:119)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:199)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:119)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1292)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1292)
        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
        at org.ehrbase.openehr.sdk.serialisation.jsonencoding.CanonicalJson.unmarshal(CanonicalJson.java:141)
        ... 2 more`

**Comment by abhinandkrish** [comment]
On examining the raw composition in [rawComp.json.zip](https://github.com/ehrbase/ehrbase/files/12565645/rawComp.json.zip)
I found the composition was created using the example composition generation url ```{{ehrbase_url}}/ehrbase/rest/ecis/v1/template/{{templae_id}}/example```

the example composition generated by the api in the older version can be successfully posted in 
both instances 
A) older version
```
<status>
<ehrbase_version>0.22.0</ehrbase_version>
<openehr_sdk_version>1.23.0</openehr_sdk_version>
<archie_version>2.0.1</archie_version>
<jvm_version>Oracle Corporation 11.0.16+8</jvm_version>
<os_version>Linux amd64 5.15.107+</os_version>
<postgres_version>PostgreSQL 14.7 (Ubuntu 14.7-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit</postgres_version>
</status>
```
B) newer version
```
<status>
<ehrbase_version>0.31.0-SNAPSHOT</ehrbase_version>
<openehr_sdk_version>2.3.0-SNAPSHOT</openehr_sdk_version>
<archie_version>3.3.0</archie_version>
<jvm_version>Eclipse Adoptium 17.0.8.1+1</jvm_version>
<os_version>Linux amd64 5.15.49-linuxkit</os_version>
<postgres_version>PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit</postgres_version>
</status>
```
But the composition is unable to be retrieved back. 
[failingComp.json.zip](https://github.com/ehrbase/ehrbase/files/12565665/failingComp.json.zip)

The example composition generated by latest versions on posting can be retrieved back in both versions.
[passingComp.json.zip](https://github.com/ehrbase/ehrbase/files/12565674/passingComp.json.zip)

**Comment by vladislavploaia** [comment]
Hello @abhinandkrish,
I was able to get back the composition.
Used below endpoint to Commit composition:
POST http://localhost:8080/ehrbase/rest/openehr/v1/ehr/{ehr_id}/composition
Headers: {"Accept": "application/json", "Content-Type": "application/json", "Prefer": "return=representation"}
Used below endpoint to Get example of composition:
http://localhost:8080/ehrbase/rest/openehr/v1/definition/template/adl1.4/tacten.mb.v0/example
I suggest to use the same endpoints, to avoid such issues.
Was able to:
1. GET http://localhost:8080/ehrbase/rest/ecis/v1/composition/{compo_id}?format=JSON
![image](https://github.com/ehrbase/ehrbase/assets/100927963/9d1dfed2-c85a-48ba-9a79-1804084e54f6)
2. GET http://localhost:8080/ehrbase/rest/openehr/v1/ehr/{ehr_id}/composition/{compo_id}
![image](https://github.com/ehrbase/ehrbase/assets/100927963/f117ddc1-ed9d-438d-813d-37721e32c73f)

Tested on EHRbase 0.31.0-SNAPSHOT.
Will keep ticket for 1-2 days, in case there are any other questions, after that it will be closed.
No issue there.
CC: @vidi42 , @stefanspiska
