### ISSUE TITLE
Error when running the dockercompose file

### ISSUE THREAD

**Issue by Meelzak** [ehrbase/ehrbase#1304]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

version: '3'

#
# Minimal setup for a running EHRbase. Contains the server component as well as the required postgres instance.
#
services:

  #
  # EHRBase container. see `.env.ehrbase` for configuration details.
  #
  ehrbase:
    image: ${EHRBASE_IMAGE:-ehrbase/ehrbase:2.0.0}
    env_file:
      - .env.ehrbase
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
    links:
      - ehrdb
    depends_on:
      ehrdb:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - ehrbase-net

  #
  # Pre-configured ehrbase postgres.
  #
  ehrdb:
    image: ${EHRBASE_POSTGRES_IMAGE:-ehrbase/ehrbase-v2-postgres:16.2}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "5432:5432"
    networks:
      - ehrbase-net

networks:
  ehrbase-net: {}

### Steps to reproduce

I've run this docker compose file as all in one and also run the docker files separately.
The postgres image works fine but when I run the ehrbase image it crashes.

I get the following error when booting up the ehrbase image:
| Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V2__ehr.sql failed
localenvironment-ehrbase-1  | ----------------------------
localenvironment-ehrbase-1  | SQL State  : 42883
localenvironment-ehrbase-1  | Error Code : 0
localenvironment-ehrbase-1  | Message    : ERROR: function ext.versioning() does not exist
localenvironment-ehrbase-1  | Location   : db/migration/V2__ehr.sql (/file:/ehrbase.jar!/BOOT-INF/lib/base-0.33.0-SNAPSHOT.jar!/db/migration/V2__ehr.sql)
localenvironment-ehrbase-1  | Line       : 146
localenvironment-ehrbase-1  | Statement  : CREATE TRIGGER versioning_trigger BEFORE INSERT OR UPDATE OR DELETE ON ehr.status
localenvironment-ehrbase-1  | FOR EACH ROW EXECUTE PROCEDURE ext.versioning('sys_period', 'ehr.status_history', true)
localenvironment-ehrbase-1  |
localenvironment-ehrbase-1  |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
localenvironment-ehrbase-1  |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
localenvironment-ehrbase-1  |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)

### Expected behavior

Docker image up and running

### Actual result

 Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V2__ehr.sql failed

**Comment by Meelzak** [comment]
Nevermind, after I deleted all my docker containers and images I pulled them again from the server. Now it is working.
