### ISSUE TITLE
Broken Accept header for GET template/adl1.4

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#279]
Recently I pulled the last develop branch.

The FHIR bridge uses a check for OPT existence when it starts, and that started to fail with the last pull of EHRBASE. The cause is the FHIR bridge uses the client lib to call the API, and the client lib is sending this header/value:  Accept: application/xml; charset=ISO-8859-1

In the last version of EHRBASE, if the charset is present in the Accept header, it fails with an exception:

```
Failure in @ExceptionHandler org.ehrbase.rest.openehr.controller.OpenehrTemplateController#restErrorHandler(ObjectNotFoundException)
org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:312)
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:123)
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:407)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:61)
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:141)
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80)
```

I tried commits from previous dates from EHRSERVER because this was working OK previously and no changes to the FHIR bridge or client library were done in this area. This commit from July 14th works OK:

```
$ git log -n 20
$ git checkout fbc4c97f85faeed04461e43efe248225b1ecbd1b
$ mvn clean install
$ java -jar application/target/application-0.13.0.jar
```

This works OK, gives 404 not found: 

```
curl --request GET \
  --url http://localhost:8080/ehrbase/rest/openehr/v1/definition/template/adl1.4/Diagnose \
  --header 'accept: application/xml; charset=ISO-8859-1'
```

**Because of that, I think this issue is a regression**

@Geisterfalle would be useful to have unit tests in the EHRSERVER testing the controllers for correct values in the headers.

![Commits · ehrbase ehrbase](https://user-images.githubusercontent.com/1278556/87817459-58691d00-c83f-11ea-8fd4-11b4edb1c7b8.png)

**Comment by Geisterfalle** [comment]
My understanding is that https://github.com/ehrbase/openEHR_SDK/pull/55 does not fix the issue from the EHRbase perspective. Hence, I would still consider this bug as being an open issue.

**Comment by ppazos** [comment]
@Geisterfalle from what @jakesmolka mentioned, he was correct: the header wasn't sent correctly from the client lib, the only part that might be missing from the ehrbase perspective is: it shouldn't return 500 but an error related with the bad header with a 4xx status.

From the SDK perspective, this is fixed with Jake's PR.

**Comment by ppazos** [comment]
2020-07-28: re-tested for https://github.com/ehrbase/project_management/issues/319

It is returning a normal result even is I send a wrong value for the Accept header including the charset data.

I also tested more values, for:
- Accept: xml I get 406 and empty response
- Accept: text/xml I get 406 and an XML response with the error
- Accept: application/json I get 400 and a JSON error

The structures of the JSON and XML errors are different. IMO should be the same data just different format.

Also for the 406 I guess both should return an error, but in some cases the response is empty.


Reference:

XML error response:

```
<?xml version='1.0' encoding='UTF-8'?>
<Map>
  <timestamp>2020-07-29T03:58:41.745+00:00</timestamp>
  <status>406</status>
  <error>Not Acceptable</error>
  <message></message>
  <path>/ehrbase/rest/openehr/v1/definition/template/adl1.4/Diagnose</path>
</Map>
```

JSON error response:

```
{
  "error": "Requested operational template type not supported",
  "status": "Bad Request"
}
```

**Comment by jakesmolka** [comment]
@ppazos @Geisterfalle I'm not sure if there's still an error or bug here. The situation is a bit complicated:

The outer layer is the Spring Framework and the inner layer is our programming. Requests are going from the outer into the inner layer during their processing.

If the problem occurs on the the outer / Spring Framework layer:
A lot of the cases here are handled by the framework. For instance, posting with a sane but invalid `Accept: text/xml` gets a somewhat good XML formatted 406 response. While "gibberish" like `Accept: application/graphql` gets an empty 406 response. 
To my knowledge that's nothing we actively handle our self in EHRbase, those are just Spring Boot MVC defaults (triggered by our API definition, i.e. that specific headers are okay). I could imagine, that the `Accept: text/xml` has at least XML in it and Spring therefore gives at least some XML as response. On the other hand, a client requesting `Accept: application/graphql` doesn't get any body, because why should it? It probably wouldn't know how to handle it anyway, and hence is requesting something else.

Of course we could change everything on that layer, but we would need to discuss that thoroughly as they are Spring Boot standards for a reason.

If the request has valid API conformance and therefore passes the outer layer:
All controllers share one error handler, which creates errors like this:
```
{
  "error": "Requested operational template type not supported",
  "status": "Bad Request"
}
```
It does that in JSON and XML, in an equivalent/compatible way. I see no problem here. 
The reference example from @ppazos above seems to show two incompatible requests, which are not directly comparable as they "fail" on different layers.

We can easily change this/our error response format, without a very deep discussion.

So, apart from that I see that we have mismatch between those two layers for sure. Would be great if all outgoing responses and errors where streamlined and of unified format. But that's a bigger issue than just a bug ticket and I'll set this issue on blocked for now, until we decide to have that discussion.

**Comment by ppazos** [comment]
@jakesmolka I'm not an expert on Spring Boot, I read a little and there are default errors, but you can also set your own handlers so errors are passed to code you can control https://www.toptal.com/java/spring-boot-rest-api-error-handling

From your comment on a shared error handler, maybe each controller associated to the API could have it's specific error handler, I think this could help to handle headers, because each endpoint requires or manages different headers, though there are some shared ones between many services.

Maybe @stefanspiska has an opinion on this area.

**Comment by jakesmolka** [comment]
@ppazos Exactly, that's what I was saying with "Of course we could change everything on that layer" :)

Technically, each endpoint can have or even has a distinct definition of its interface, e.g. what headers to accept and so on. So that's already happening. But still, everything that goes beyond that will be caught in the Spring Boot layer and handled there.

I'm not sure on how to top-level design Spring Boot applications. But it would probably make sense to unify all the responses and errors. Hopefully there's a way to just inject a custom format for the error response. We would gain a lot regarding UX just with a unified format I think.

Anyway, this issue need to be put back into the backlog for now.

**Comment by Geisterfalle** [comment]
TODO:
-create acceptance criteria
-investigate solution

**Comment by wlad** [comment]
I ran into this issue, too, recently.

I noticed that sending a GET request to `/definition/template/adl1.4/${template_id}` without specifying any headers results in
```
{
  "error": "Requested operational template type not supported",
  "status": "Bad Request"
}
```

I'd expect the server to fallback to any working default instead of returning this error.
