### ISSUE TITLE
Validation fail on mvn clean install

### ISSUE THREAD

**Issue by freshehr** [ehrbase/ehrbase#282]
v.0.13.0 mvn clean install on osx 10.15.6. 

Everything else building normally AFAICT.

```
Running org.ehrbase.validation.ItemStructureVisitorTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.699 sec - in org.ehrbase.validation.ItemStructureVisitorTest

Results :

Tests in error: 
  ValidatorTest.testValidateComposition1:43 » NoClassDefFound Could not initiali...
  ValidatorTest.testValidateComposition2:56 » NoClassDefFound Could not initiali...
  ValidatorTest.testValidateCompositionBadValueCodedText:83 » NoClassDefFound Co...
  ValidatorTest.testValidateCompositionOKCodedText:97 » NoClassDefFound Could no...
  ValidatorTest.testValidateCompositionWithBadCodePhrase:69 » NoClassDefFound Co...
  ValidatorTest.testValidateRippleConformance:110 » NoClassDefFound Could not in...
  ValidatorTest.testValidateTestAllTypes:123 » ExceptionInInitializer
  DvBooleanTest.setUp:33->ConstraintTestBase.setUpContext:37 » ExceptionInInitializer
  DvBooleanTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound C...
  DvCodedTextTest.setUp:34->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvCodedTextTest.setUp:34->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvCodedTextTest.setUp:34->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvCountTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound Cou...
  DvCountTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound Cou...
  DvDateTimeTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound ...
  DvDurationTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound ...
  DvIdentifierTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvIntervalDvCountTest.setUp:34->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvIntervalDvDateTimeTest.setUp:36->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvIntervalDvQuantityTest.setUp:34->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvMultimediaTest.setUp:36->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvOrdinalTest.setUp:36->ConstraintTestBase.setUpContext:37 » NoClassDefFound C...
  DvProportionTest.setUp:34->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvProportionTest.setUp:34->ConstraintTestBase.setUpContext:37 » NoClassDefFound
  DvQuantityTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound ...
  DvQuantityTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound ...
  DvQuantityTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound ...
  DvUriTest.setUp:33->ConstraintTestBase.setUpContext:37 » NoClassDefFound Could...
  ElementTest.setUp:37->ConstraintTestBase.setUpContext:37 » NoClassDefFound Cou...
  OptConstraintTest.testLoadOperationalTemplate:33 » NoClassDefFound Could not i...
```

**Comment by stefanspiska** [comment]
Works for me. 
What is shown behind   `NoClassDefFound Could...` ?

**Comment by freshehr** [comment]
Thanks @stefanspiska 

```
<<< FAILURE! - in org.ehrbase.validation.ValidatorTest
testValidateTestAllTypes(org.ehrbase.validation.ValidatorTest)  Time elapsed: 0.661 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
        at org.ehrbase.validation.ValidatorTest.testValidateTestAllTypes(ValidatorTest.java:123)
Caused by: java.lang.RuntimeException: Cannot load SchemaTypeSystem. Unable to load class with name schemaorg_apache_xmlbeans.system.s3134DD99BD0D67F2DD35F8BA3A039407.TypeSystemHolder. Make sure the generated binary files are on the classpath.
        at org.ehrbase.validation.ValidatorTest.testValidateTestAllTypes(ValidatorTest.java:123)
Caused by: java.lang.ClassNotFoundException: schemaorg_apache_xmlbeans.system.s3134DD99BD0D67F2DD35F8BA3A039407.TypeSystemHolder
        at org.ehrbase.validation.ValidatorTest.testValidateTestAllTypes(ValidatorTest.java:123)

testValidateCompositionBadValueCodedText(org.ehrbase.validation.ValidatorTest)  Time elapsed: 0.061 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.openehr.schemas.v1.TemplateDocument
        at org.ehrbase.validation.ValidatorTest.testValidateCompositionBadValueCodedText(ValidatorTest.java:83)
```

I am investigating https://stackoverflow.com/questions/8518301/error-when-using-xmlbeans-generated-classes

**Comment by freshehr** [comment]
Complied ok on a Linux vm so looks like some sort of macos setup issue.

**Comment by freshehr** [comment]
Turned out to be config issue on macOS - can be closed
