### ISSUE TITLE
Internal Server Error and Startup Failure on Posting Template

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#358]
## Steps to reproduce ## 
I'm using the following docker-compose file:
```yml
version: "3"
services:
    ehrbase:
        image: ehrbaseorg/ehrbase:next
        ports:
            - "8080:8080"
        environment: 
            - DB_URL=jdbc:postgresql://db:5432/ehrbase
            - DB_USER=ehrbase
            - DB_PASS=ehrbase
            - SYSTEM_NAME=local.ehrbase.org
        depends_on: 
            - db
    db:
        image: ehrbaseorg/ehrbase-postgres:latest
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_PASSWORD=postgres

```

I made a POST to `http://localhost:8080/ehrbase/rest/openehr/v1/definition/template/adl1.4/`
with the template [provided here](https://0bin.net/paste/f-6XtfRv#4S-p0T0RIYm1O6YR8m46cDvX+xIXQm9kAuVjPC3aghz).

## Actual result ##
Server responds with 
```
{
  "error": "Internal Server Error: null",
  "status": "Internal Server Error"
}
```
The output of the docker ehrbase container:
```
ehrbase_1  | 2020-11-04 07:34:23.329  INFO 8 --- [nio-8080-exec-1] o.ehrbase.service.KnowledgeCacheService  : Updating WebTemplate cache for template: blood_pressure_template
```
However, I'm able to GET the template but posting again causes a conflict error.
Posting any composition at `http://localhost:8080/ehrbase/rest/ecis/v1/composition/?format=FLAT` with `templateId=blood_pressure_template` causes an internal server error:
```
{
  "error": "Internal Server Error: null",
  "status": "Internal Server Error"
}
```
After this, restarting EHRBase errors out on start-up:
```
ehrbase_1  | 2020-11-04 07:36:56.392  INFO 8 --- [           main] o.ehrbase.service.KnowledgeCacheService  : Updating WebTemplate cache for template: blood_pressure_template
ehrbase_1  | 2020-11-04 07:36:56.737  WARN 8 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'templateServiceImp' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.14.0.jar!/org/ehrbase/service/TemplateServiceImp.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'knowledgeCacheService': Invocation of init method failed; nested exception is org.ehrbase.api.exception.InternalServerException
ehrbase_1  | 2020-11-04 07:36:56.741  INFO 8 --- [           main] org.ehcache.core.EhcacheManager          : Cache 'operationaltemplateCache' removed from EhcacheManager.
ehrbase_1  | 2020-11-04 07:36:56.767  INFO 8 --- [           main] org.ehcache.core.EhcacheManager          : Cache 'introspectCache' removed from EhcacheManager.
ehrbase_1  | 2020-11-04 07:36:56.784  INFO 8 --- [           main] org.ehcache.core.EhcacheManager          : Cache 'multivaluedCache' removed from EhcacheManager.
ehrbase_1  | 2020-11-04 07:36:56.807  INFO 8 --- [           main] org.ehcache.core.EhcacheManager          : Cache 'queryCache' removed from EhcacheManager.
ehrbase_1  | 2020-11-04 07:36:56.824  INFO 8 --- [           main] org.ehcache.core.EhcacheManager          : Cache 'fieldsCache' removed from EhcacheManager.
ehrbase_1  | 2020-11-04 07:36:56.825  INFO 8 --- [           main] org.ehcache.core.EhcacheManager          : Cache 'validatorCache' removed from EhcacheManager.
ehrbase_1  | 2020-11-04 07:36:56.832  INFO 8 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
ehrbase_1  | 2020-11-04 07:36:56.836  INFO 8 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
ehrbase_1  | 2020-11-04 07:36:56.852  INFO 8 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
ehrbase_1  | 2020-11-04 07:36:56.855  INFO 8 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
ehrbase_1  | 2020-11-04 07:36:56.877  INFO 8 --- [           main] ConditionEvaluationReportLoggingListener :
ehrbase_1  |
ehrbase_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
ehrbase_1  | 2020-11-04 07:36:56.881 ERROR 8 --- [           main] o.s.boot.SpringApplication               : Application run failed
ehrbase_1  |
ehrbase_1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'templateServiceImp' defined in URL [jar:file:/ehrbase.jar!/BOOT-INF/lib/service-0.14.0.jar!/org/ehrbase/service/TemplateServiceImp.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'knowledgeCacheService': Invocation of init method failed; nested exception is org.ehrbase.api.exception.InternalServerException
ehrbase_1  |    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
ehrbase_1  |    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
ehrbase_1  |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
ehrbase_1  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
ehrbase_1  |    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
ehrbase_1  |    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
ehrbase_1  |    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
ehrbase_1  |    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
ehrbase_1  |    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
ehrbase_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
ehrbase_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
ehrbase_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
ehrbase_1  |    at org.ehrbase.application.EhrBase.main(EhrBase.java:36)
ehrbase_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ehrbase_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
ehrbase_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
ehrbase_1  |    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
ehrbase_1  |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
ehrbase_1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
ehrbase_1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
ehrbase_1  |    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
ehrbase_1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'knowledgeCacheService': Invocation of init method failed; nested exception is org.ehrbase.api.exception.InternalServerException
ehrbase_1  |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
ehrbase_1  |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
ehrbase_1  |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
ehrbase_1  |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
ehrbase_1  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
ehrbase_1  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
ehrbase_1  |    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
ehrbase_1  |    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
ehrbase_1  |    ... 27 common frames omitted
ehrbase_1  | Caused by: org.ehrbase.api.exception.InternalServerException: null
ehrbase_1  |    at org.ehrbase.service.KnowledgeCacheService.buildAndCacheQueryOptMetaData(KnowledgeCacheService.java:384)
ehrbase_1  |    at org.ehrbase.service.KnowledgeCacheService.buildAndCacheQueryOptMetaData(KnowledgeCacheService.java:371)
ehrbase_1  |    at org.ehrbase.service.KnowledgeCacheService.getQueryOptMetaData(KnowledgeCacheService.java:351)
ehrbase_1  |    at org.ehrbase.service.KnowledgeCacheService.getQueryOptMetaData(KnowledgeCacheService.java:359)
ehrbase_1  |    at org.ehrbase.service.KnowledgeCacheService.putIntoCache(KnowledgeCacheService.java:238)
ehrbase_1  |    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
ehrbase_1  |    at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
ehrbase_1  |    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
ehrbase_1  |    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
ehrbase_1  |    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
ehrbase_1  |    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
ehrbase_1  |    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
ehrbase_1  |    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
ehrbase_1  |    at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
ehrbase_1  |    at org.ehrbase.service.KnowledgeCacheService.init(KnowledgeCacheService.java:147)
ehrbase_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ehrbase_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
ehrbase_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
ehrbase_1  |    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
ehrbase_1  |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
ehrbase_1  |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
ehrbase_1  |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
ehrbase_1  |    ... 40 common frames omitted
ehrbase_1  | Caused by: java.lang.NullPointerException: null
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCDOMAINTYPE(OPTParser.java:419)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCOBJECT(OPTParser.java:356)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCCOMPLEXOBJECT(OPTParser.java:138)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCOBJECT(OPTParser.java:346)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCCOMPLEXOBJECT(OPTParser.java:138)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCOBJECT(OPTParser.java:346)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCCOMPLEXOBJECT(OPTParser.java:138)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCOBJECT(OPTParser.java:346)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCCOMPLEXOBJECT(OPTParser.java:138)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCOBJECT(OPTParser.java:346)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCCOMPLEXOBJECT(OPTParser.java:138)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCOBJECT(OPTParser.java:346)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCCOMPLEXOBJECT(OPTParser.java:138)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCARCHETYPEROO(OPTParser.java:103)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCOBJECT(OPTParser.java:336)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCCOMPLEXOBJECT(OPTParser.java:138)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parseCARCHETYPEROO(OPTParser.java:103)
ehrbase_1  |    at org.ehrbase.webtemplate.parser.OPTParser.parse(OPTParser.java:81)
ehrbase_1  |    at org.ehrbase.service.KnowledgeCacheService.buildAndCacheQueryOptMetaData(KnowledgeCacheService.java:382)
ehrbase_1  |    ... 61 common frames omitted
ehrbase_1  |
ehrbase_ehrbase_1 exited with code 1
```
## Expected result ##
- Accept the template and return 201 or throw a useful error and reject the template completely
- Accept the composition and return 201 or throw a useful error
- Start-up EHRBase normally without requiring a database reset

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by sidharthramesh** [comment]
The template has been generated using https://tools.openehr.org/designer/

**Comment by freshehr** [comment]
@sidharthramesh - re the 409 error - this is correct since the current openEHR spec says that you cannot overwrite a template but it is annoying in development stages - there is a configuration setting in EHRbase that switches this behaviour off but you will need to restart the service.

Can you attach or give access to the Fileset export - basically a zip file with the template and archetypes?
I can load the .opt here but I am getting an odd error when I try to save an example composition in the Better CDR. I'd need access to the  original artefacts to see more.

**Comment by sidharthramesh** [comment]
Sure. I'll upload it by tomorrow. The issue is not about the 409 conflict error. It's about the 500 error that I'm getting when I post a template for the very first time. This error only happens when I use Better's Archetypes designer to output the template. I've tried Ocean's template designer and there is no issue.

**Comment by sidharthramesh** [comment]
@freshehr Here is the fileset export you asked for. This has been exported from https://tools.openehr.org/

[Blood pressure template.zip](https://github.com/ehrbase/ehrbase/files/5492545/Blood.pressure.template.zip)

**Comment by freshehr** [comment]
@sidharthramesh - I have not tested it yet but my guess is that the problem is because you have set an external valueset for Physical activity but have not specified a terminology or url. Just put in SNOMED-CT for terminology and some dummy string like 'PhysicalActivitytype' as the valueset

**Comment by stefanspiska** [comment]
With https://github.com/ehrbase/ehrbase/pull/359
the template is now rejected instead of saved in the db.
Also it is now posable to start ehrbase even with  non working templates, so those can be removed via the admin Interface.

**Comment by sidharthramesh** [comment]
@freshehr you are absolutely right. It's because of me not mentioning the terminology.

@stefanspiska I can confirm that it does reject my template now.

I will close the issue.
