### ISSUE TITLE
Error parsing HTTP request header

### ISSUE THREAD

**Issue by CzarMich** [ehrbase/ehrbase#607]
## Configuration information

- EHRbase version:   v0.17.2
- openEHR_SDK version:  1.5.0
- PostgreSQL version:  v10
- Java Runtime version: openJDK 11
- Operating System version: Ubuntu 20

## Steps to reproduce ## 

Running:  $ java -jar application/target/application-0.17.2.jar

## Actual result ##

2021-09-28 13:55:44.370  INFO 2025829 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path '/ehrbase'
2021-09-28 13:55:44.376  INFO 2025829 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2021-09-28 13:55:44.416  INFO 2025829 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2021-09-28 13:55:44.701  INFO 2025829 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2021-09-28 13:55:44.747  INFO 2025829 --- [           main] DeferredRepositoryInitializationListener : Triggering deferred initialization of Spring Data repositories…
2021-09-28 13:55:44.749  INFO 2025829 --- [           main] DeferredRepositoryInitializationListener : Spring Data repositories initialized!
2021-09-28 13:55:44.798  INFO 2025829 --- [           main] org.ehrbase.application.EhrBase          : Started EhrBase in 18.937 seconds (JVM running for 20.248)
2021-09-28 13:56:33.625  INFO 2025829 --- [nio-8080-exec-1] o.a.c.c.C.[.[localhost].[/ehrbase]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-09-28 13:56:33.627  INFO 2025829 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-09-28 13:56:33.704  INFO 2025829 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 76 ms
2021-09-28 14:14:25.101  INFO 2025829 --- [nio-8080-exec-5] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xe00xac0x8d0x97RaJ0xd8L60xcaz0xcc,0x1d0xa50x1c!y0xab0xf60xd70x1c0x1aQ0xcfV0xcc{0xd40x9c0x1b]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

## Definition of Done ##

Run: $ netstat -ntlp | grep LISTEN
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp6       0      0 ::1:631                 :::*                    LISTEN      -                   
tcp6       0      0 :::8080                 :::*                    LISTEN      2025829/java

**Comment by maximni-vg** [comment]
Hello @CzarMich,

Does this error occur when starting EHRbase, or are you actually sending a request to EHRbase here? If its the latter, could you please also add information for the request you're sending?
The error message indicates that an inbound request could not be parsed.

**Comment by CzarMich** [comment]
> 

Hi Maxim, I can't recall well but this was fixed. I made some changes I cannot recall now though.

**Comment by maximni-vg** [comment]
Thank you for the reply, I would close this issue then.
If you see this error again, feel free to (re-)open the issue.
