### ISSUE TITLE
POST /composition strange XML serialization in the response

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#611]
## Configuration information

```
<status>
  <ehrbase_version>0.17.2</ehrbase_version>
  <openehr_sdk_version>bc7e213</openehr_sdk_version>
  <archie_version>1.0.3</archie_version>
  <jvm_version>Oracle Corporation 11.0.6+10</jvm_version>
  <os_version>Linux amd64 4.15.0-91-generic</os_version>
  <postgres_version>PostgreSQL 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>
</status>
```

## Steps to reproduce ## 

This is the request and reponse (formatted response below)

```
POST /ehrbase/rest/openehr/v1/ehr/9e393d34-1401-40d0-8408-c294fa96b3b2/composition HTTP/1.1
Host: localhost:8080
User-Agent: python-requests/2.22.0
Accept-Encoding: gzip, deflate
Accept: application/xml
Connection: keep-alive
Content-Type: application/xml
Prefer: return=representation
Content-Length: 3209
Authorization: Basic ZWhyYmFzZS11c2VyOlN1cGVyU2VjcmV0UGFzc3dvcmQ=
  <composition xmlns="http://schemas.openehr.org/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="COMPOSITION" archetype_node_id="openEHR-EHR-COMPOSITION.persistent_minimal.v1">
    <name>
      <value>Persistent minimal</value>
    </name>
    <archetype_details>
      <archetype_id>
        <value>openEHR-EHR-COMPOSITION.persistent_minimal.v1</value>
      </archetype_id>
      <template_id>
        <value>persistent_minimal.en.v1</value>
      </template_id>
      <rm_version>1.0.2</rm_version>
    </archetype_details>
    <language>
      <terminology_id>
        <value>ISO_639-1</value>
      </terminology_id>
      <code_string>en</code_string>
    </language>
    <territory>
      <terminology_id>
        <value>ISO_3166-1</value>
      </terminology_id>
      <code_string>UY</code_string>
    </territory>
    <category>
      <value>persistent</value>
      <defining_code>
        <terminology_id>
          <value>openehr</value>
        </terminology_id>
        <code_string>431</code_string>
      </defining_code>
    </category>
    <composer xsi:type="PARTY_IDENTIFIED">
      <external_ref>
        <id xsi:type="HIER_OBJECT_ID">
          <value>a3dce0d4-fa51-4ff2-9cce-93dd60437842</value>
        </id>
        <namespace>DEMOGRAPHIC</namespace>
        <type>PERSON</type>
      </external_ref>
      <name>Dr. Yamamoto</name>
    </composer>
    <content archetype_node_id="openEHR-EHR-OBSERVATION.minimal.v1" xsi:type="OBSERVATION">
      <archetype_details>
        <archetype_id>
          <value>openEHR-EHR-OBSERVATION.minimal.v1</value>
        </archetype_id>
        <template_id>
          <value>persistent_minimal.en.v1</value>
        </template_id>
        <rm_version>1.0.2</rm_version>
      </archetype_details>
      <name>
        <value>Minimal</value>
      </name>
      <language>
        <terminology_id>
          <value>ISO_639-1</value>
        </terminology_id>
        <code_string>en</code_string>
      </language>
      <encoding>
        <terminology_id>
          <value>IANA_character-sets</value>
        </terminology_id>
        <code_string>UTF-8</code_string>
      </encoding>
      <subject xsi:type="PARTY_SELF" />
      <data archetype_node_id="at0001" xsi:type="HISTORY">
        <name>
          <value>Event Series</value>
        </name>
        <origin xsi:type="DV_DATE_TIME">
          <value>2019-04-16T21:08:11,380+0000</value>
        </origin>
        <events archetype_node_id="at0002" xsi:type="POINT_EVENT">
          <name>
            <value>Cualquier evento</value>
          </name>
          <time xsi:type="DV_DATE_TIME">
            <value>2019-04-16T21:08:11,384+0000</value>
          </time>
          <data archetype_node_id="at0003" xsi:type="ITEM_TREE">
            <name>
              <value>Arbol</value>
            </name>
            <items archetype_node_id="at0004" xsi:type="ELEMENT">
              <name>
                <value>text</value>
              </name>
              <value xsi:type="DV_TEXT">
                <value>original value</value>
              </value>
            </items>
          </data>
        </events>
      </data>
    </content>
  </composition>
HTTP/1.1 201 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Location: http://localhost:8080/ehrbase/rest/openehr/v1/ehr/9e393d34-1401-40d0-8408-c294fa96b3b2/composition/891e0525-08c7-4a37-9921-057d3b3d0884
ETag: "891e0525-08c7-4a37-9921-057d3b3d0884::local.ehrbase.org::1"
Last-Modified: Fri, 02 Jan 1970 10:12:04 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/xml
Content-Length: 2889
Date: Wed, 29 Sep 2021 19:33:24 GMT
Keep-Alive: timeout=60
Connection: keep-alive
<composition archetype_node_id="openEHR-EHR-COMPOSITION.persistent_minimal.v1" xmlns:ns2="http://schemas.openehr.org/v1"><name><value>Persistent minimal</value></name><uid xsi:type="OBJECT_VERSION_ID" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><value>891e0525-08c7-4a37-9921-057d3b3d0884::local.ehrbase.org::1</value></uid><archetype_details><archetype_id><value>openEHR-EHR-COMPOSITION.persistent_minimal.v1</value><qualifiedRmEntity>openEHR-EHR-COMPOSITION</qualifiedRmEntity><domainConcept>persistent_minimal</domainConcept><rmOriginator>openEHR</rmOriginator><rmName>EHR</rmName><rmEntity>COMPOSITION</rmEntity><versionId>1</versionId></archetype_id><template_id><value>persistent_minimal.en.v1</value></template_id><rm_version>1.0.2</rm_version></archetype_details><language><terminology_id><value>ISO_639-1</value></terminology_id><code_string>en</code_string></language><territory><terminology_id><value>ISO_3166-1</value></terminology_id><code_string>UY</code_string></territory><category><value>persistent</value><defining_code><terminology_id><value>openehr</value></terminology_id><code_string>431</code_string></defining_code></category><composer xsi:type="PARTY_IDENTIFIED" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><external_ref><id xsi:type="HIER_OBJECT_ID"><value>a3dce0d4-fa51-4ff2-9cce-93dd60437842</value></id><namespace>DEMOGRAPHIC</namespace><type>PERSON</type></external_ref><name>Dr. Yamamoto</name></composer><content xsi:type="OBSERVATION" archetype_node_id="openEHR-EHR-OBSERVATION.minimal.v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><name><value>Minimal</value></name><archetype_details><archetype_id><value>openEHR-EHR-OBSERVATION.minimal.v1</value><qualifiedRmEntity>openEHR-EHR-OBSERVATION</qualifiedRmEntity><domainConcept>minimal</domainConcept><rmOriginator>openEHR</rmOriginator><rmName>EHR</rmName><rmEntity>OBSERVATION</rmEntity><versionId>1</versionId></archetype_id><template_id><value>persistent_minimal.en.v1</value></template_id><rm_version>1.0.2</rm_version></archetype_details><language><terminology_id><value>ISO_639-1</value></terminology_id><code_string>en</code_string></language><encoding><terminology_id><value>IANA_character-sets</value></terminology_id><code_string>UTF-8</code_string></encoding><subject xsi:type="PARTY_SELF"/><data archetype_node_id="at0001"><name><value>Event Series</value></name><origin><value>2019-04-16T21:08:11.380Z</value></origin><events xsi:type="POINT_EVENT" archetype_node_id="at0002"><name><value>Cualquier evento</value></name><time><value>2019-04-16T21:08:11.384Z</value></time><data xsi:type="ITEM_TREE" archetype_node_id="at0003"><name><value>Arbol</value></name><items xsi:type="ELEMENT" archetype_node_id="at0004"><name><value>text</value></name><value xsi:type="DV_TEXT"><value>original value</value></value></items></data></events></data></content></composition>
```

Formatted reaponse:

```
<composition archetype_node_id="openEHR-EHR-COMPOSITION.persistent_minimal.v1"
    xmlns:ns2="http://schemas.openehr.org/v1">
    <name>
        <value>Persistent minimal</value>
    </name>
    <uid xsi:type="OBJECT_VERSION_ID"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <value>891e0525-08c7-4a37-9921-057d3b3d0884::local.ehrbase.org::1</value>
    </uid>
    <archetype_details>
        <archetype_id>
            <value>openEHR-EHR-COMPOSITION.persistent_minimal.v1</value>
            <qualifiedRmEntity>openEHR-EHR-COMPOSITION</qualifiedRmEntity>
            <domainConcept>persistent_minimal</domainConcept>
            <rmOriginator>openEHR</rmOriginator>
            <rmName>EHR</rmName>
            <rmEntity>COMPOSITION</rmEntity>
            <versionId>1</versionId>
        </archetype_id>
        <template_id>
            <value>persistent_minimal.en.v1</value>
        </template_id>
        <rm_version>1.0.2</rm_version>
    </archetype_details>
    <language>
        <terminology_id>
            <value>ISO_639-1</value>
        </terminology_id>
        <code_string>en</code_string>
    </language>
    <territory>
        <terminology_id>
            <value>ISO_3166-1</value>
        </terminology_id>
        <code_string>UY</code_string>
    </territory>
    <category>
        <value>persistent</value>
        <defining_code>
            <terminology_id>
                <value>openehr</value>
            </terminology_id>
            <code_string>431</code_string>
        </defining_code>
    </category>
    <composer xsi:type="PARTY_IDENTIFIED"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <external_ref>
            <id xsi:type="HIER_OBJECT_ID">
                <value>a3dce0d4-fa51-4ff2-9cce-93dd60437842</value>
            </id>
            <namespace>DEMOGRAPHIC</namespace>
            <type>PERSON</type>
        </external_ref>
        <name>Dr. Yamamoto</name>
    </composer>
    <content xsi:type="OBSERVATION" archetype_node_id="openEHR-EHR-OBSERVATION.minimal.v1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <name>
            <value>Minimal</value>
        </name>
        <archetype_details>
            <archetype_id>
                <value>openEHR-EHR-OBSERVATION.minimal.v1</value>
                <qualifiedRmEntity>openEHR-EHR-OBSERVATION</qualifiedRmEntity>
                <domainConcept>minimal</domainConcept>
                <rmOriginator>openEHR</rmOriginator>
                <rmName>EHR</rmName>
                <rmEntity>OBSERVATION</rmEntity>
                <versionId>1</versionId>
            </archetype_id>
            <template_id>
                <value>persistent_minimal.en.v1</value>
            </template_id>
            <rm_version>1.0.2</rm_version>
        </archetype_details>
        <language>
            <terminology_id>
                <value>ISO_639-1</value>
            </terminology_id>
            <code_string>en</code_string>
        </language>
        <encoding>
            <terminology_id>
                <value>IANA_character-sets</value>
            </terminology_id>
            <code_string>UTF-8</code_string>
        </encoding>
        <subject xsi:type="PARTY_SELF"/>
        <data archetype_node_id="at0001">
            <name>
                <value>Event Series</value>
            </name>
            <origin>
                <value>2019-04-16T21:08:11.380Z</value>
            </origin>
            <events xsi:type="POINT_EVENT" archetype_node_id="at0002">
                <name>
                    <value>Cualquier evento</value>
                </name>
                <time>
                    <value>2019-04-16T21:08:11.384Z</value>
                </time>
                <data xsi:type="ITEM_TREE" archetype_node_id="at0003">
                    <name>
                        <value>Arbol</value>
                    </name>
                    <items xsi:type="ELEMENT" archetype_node_id="at0004">
                        <name>
                            <value>text</value>
                        </name>
                        <value xsi:type="DV_TEXT">
                            <value>original value</value>
                        </value>
                    </items>
                </data>
            </events>
        </data>
    </content>
</composition>
```

## Actual result ##

I'm not a XML expert, though these look strange.

I think formally the declaration of the ns2 namespace (xmlns:ns2="http://schemas.openehr.org/v1") requires all tags to have the "ns2:" prefix, then when declaring the default namespace doesn't require the prefix (xmlns="http://schemas.openehr.org/v1"), like in the request payload.

Another thing is the xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" namespace is declared several times on different elements, if it's declared in the root, there is no need of declaring it on different internal elements.

Not sure how is this being serialized, might be something there.

## Expected result (Acceptance Criteria) ##

I'm not sure if the xsi declaration is really an issue, though the ns2 declaration I think is not right.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by subigre** [comment]
I have added the `package-info.java` with namespace declaration in all sub-packages of `com.nedap.archie`.
Unfortunately this change generates JAXBException while unmarshalling in some compositions:
```
 javax.xml.bind.UnmarshalException: Unable to create an instance of com.nedap.archie.rm.datavalues.DataValue
     - with linked exception:
    [java.lang.InstantiationException]
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:712)
        at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:232)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.createInstance(UnmarshallingContext.java:676)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:158)
        at com.sun.xml.bind.v2.runtime.unmarshaller.XsiTypeLoader.startElement(XsiTypeLoader.java:50)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:545)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:524)
        at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:137)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:170)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:209)
        at com.nedap.archie.rm.composition.CompositionTest.testEqual(CompositionTest.java:21)
        Caused by:
        java.lang.InstantiationException
            at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
            at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
            at com.sun.xml.bind.v2.ClassFactory.create0(ClassFactory.java:132)
            at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.createInstance(ClassBeanInfoImpl.java:254)
            at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.createInstance(UnmarshallingContext.java:670)
            ... 21 more
```
I suspect that the error is related to the abstract class and the missing `@XmlSeeAlso` annotation. 
I tried to add the annotation but it is not working properly classes that used generics like `DvAbsoluteQuantity`, `DvTemporal`, etc.

I would suggest to raise an issue in archie repo because Pieter Bos probably knows better how it works.

As an alternative, I think that archie should not add the namespace declaration at all if it cannot be handle correctly in all XML elements.

**Comment by ppazos** [comment]
@vladislavploaia one thing to note is in the original request the openEHR NS was the default NS but the response defined that as "ns2"

`Request NS: xmlns="http://schemas.openehr.org/v1"`

I guess it should be some documentation mentioning the XML NS will be overridden or changed at the server side.

I'm not saying this is wrong, just saying it's something a client should note.

**Comment by vladislavploaia** [comment]
Archie issue is still in review: https://github.com/openEHR/archie/issues/343
