### ISSUE TITLE
POST /directory is not accepting an empty body

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#651]
## Configuration information

<status>
  <ehrbase_version>0.17.2</ehrbase_version>
  <openehr_sdk_version>321ef09</openehr_sdk_version>
  <archie_version>1.0.3</archie_version>
  <jvm_version>Oracle Corporation 11.0.6+10</jvm_version>
  <os_version>Linux amd64 4.15.0-91-generic</os_version>
  <postgres_version>PostgreSQL 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>
</status>

## Steps to reproduce ## 

Request: change the ehr_id with an existing one.

```
curl --request POST \
  --url http://localhost:8080/ehrbase/rest/openehr/v1/ehr/4d22f7a0-6367-4588-9b1d-4ce684e1d66c/directory \
  --header 'prefer: return=representation'
```

## Actual result ##

500

```
{
  "error": "Required request header 'Content-Type' for method parameter type String is not present",
  "status": "Internal Server Error"
}
```

## Expected result (Acceptance Criteria) ##

I think it should be possible to create an empty ehr.directory.

Just in case I asked on the openEHR forum: curl --request POST \
  --url http://localhost:8080/ehrbase/rest/openehr/v1/ehr/4d22f7a0-6367-4588-9b1d-4ce684e1d66c/directory \
  --header 'prefer: return=representation'

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by ppazos** [comment]
Note:

After discussing with Thomas Beale, it seems this case shouldn't be supported by the REST API, so this issue shouldn't be considered a feature request, but as an improvement over the response.

1. It shouldn't return 500
2. The error should be about the required body not about the missing header Content-Type

An extra step would be to validate the body payload against the correspondent schema and return validation errors.

@birgerhaarbrandt @chevalleyc do you think that is reasonable?

**Comment by ppazos** [comment]
Tested on 2022-02-14 the 500 still happens, the result is slightly different than the reported above:

```
{
  "error": "Internal Server Error",
  "message": "An internal error has occurred. Please contact your administrator."
}
```

Log:

```
org.springframework.web.bind.MissingRequestHeaderException: Required request header 'Content-Type' for method parameter type String is not present
	at org.springframework.web.method.annotation.RequestHeaderMethodArgumentResolver.handleMissingValue(RequestHeaderMethodArgumentResolver.java:87)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.handleMissingValue(AbstractNamedValueMethodArgumentResolver.java:226)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:114)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.ehrbase.application.web.LoggingContextFilter.doFilterInternal(LoggingContextFilter.java:53)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by vladislavploaia** [comment]
Hello @ppazos,
Checked on EHRBase version **0.22.0** and here are few comments:
1. Status code 500 is no more returned (only 400 Bad Request)
2. If Content-Type is provided (Example: Content-Type: application/json), the following error is thrown:
![image](https://user-images.githubusercontent.com/100927963/178267808-0d3b07e8-d4bd-41ac-95d2-23a50644f09a.png)
3. If Content-Type is not provided:
![image](https://user-images.githubusercontent.com/100927963/178267939-c8c2181a-6f41-4628-a176-a6878d8c39af.png)
In both cases, no body was provided.
Do you have any documentation reference where it is explicitly said that creation of directory is possible with empty body?
Thanks in advance for your time.

**Comment by vladislavploaia** [comment]
Hello @ppazos,
Body must be provided, when creating Folder.
**Here is how EHRBase responds to empty body**
![image](https://user-images.githubusercontent.com/100927963/218094594-62a65066-fc63-4760-beec-bc5a6d8b48d9.png)
To be able to create Folder, you should provide body, as follows (example only):
![image](https://user-images.githubusercontent.com/100927963/218095413-0ad1a0bb-7e3a-42f8-8d05-82f8f5766cea.png)
Closing ticket, as nothing to fix from our side.
CC: @vidi42 , @stefanspiska , @HolgerReiseVSys

**Comment by ppazos** [comment]
@vladislavploaia is it OK that the response sends the internal exception to a client?

**Comment by vladislavploaia** [comment]
Hello @ppazos ,
As you can see, 400 Bad Request is returned.
It is saying that **Required request body is missing** - this part is ok.
Second part not sure, maybe this can be removed. We will check internally, what to return in that case, however, this will be as an improvement only (I suppose).
CC: @vidi42 , @HolgerReiseVSys , @stefanspiska

**Comment by vladislavploaia** [comment]
@ppazos , reported [bug](https://jira.vitagroup.ag/browse/CDR-738) for error message content, to not expose full internal error.
Will let you know if I have any updates on that.
Thank you!
CC: @vidi42
